name = "heart-health-ai-assistant"
main = "src/index.ts"
compatibility_date = "2024-06-06" 

# Custom domain configuration
routes = [
  { pattern = "api.cardicare.daivanlabs.site", custom_domain = true }
]

[vars]
# You will need to set your GEMINI_API_KEY as a secret in your Cloudflare dashboard
# Example: wrangler secret put GEMINI_API_KEY
# GEMINI_API_KEY = "your_api_key_here" # This is just a placeholder, set it via wrangler secret

# Optional: If you want to define environment variables for different environments
# [env.dev.vars]
# GEMINI_API_KEY = "your_dev_api_key_here"

# [env.production.vars]
# GEMINI_API_KEY = "your_prod_api_key_here" # Set this via wrangler secret put GEMINI_API_KEY --env production
