name = "drug-interaction-worker"
main = "super-simple-interaction-worker.js"
compatibility_date = "2024-06-06"

# Custom domain configuration
# routes = [
#   { pattern = "drug-interaction-worker.cardicare.daivanlabs.site", custom_domain = true }
# ]

[vars]
# Add any environment variables here if needed in the future
# Example: OPENFDA_API_KEY = "your_api_key_here"

# If you plan to use KV, R2, Durable Objects, etc., configure them here.
# For example:
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
